<?php 

// arithmetic operator(+,-,*,\,%)
$a=10;
$b=20;
echo $a+$b."<br>";
echo $a-$b."<br>";
echo $a*$b."<br>";
echo $a/$b."<br>";
echo $a%$b."<br>";

// assignment operator
$a=$b;
echo $a."<br>";

$a+=$b;
echo $a."<br>";

$a-=$b;
echo $a."<br>";

$a*=$b;
echo $a."<br>";

$a%=$b;
echo $a."<br>";

$a%=$b;
echo $a."<br>";

// comperission operator

$a=10;
$b=20;

echo $a==$b."a==b"."<br>";
echo $a===$b."a===b"."<br>";
echo $a<=$b."a<=b"."<br>";
echo $a>=$b."a>=b"."<br>";
echo $a!=$b."a!=b"."<br>";
echo $a!==$b."a!==b"."<br>";
echo $a<$b."a<b"."<br>";
echo $a>$b."a>b"."<br>";



?>